### ISSUE TITLE
BaseView.ExecuteAsync disposes the response stream

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/Diagnostics#112]
I was looking at [this line](https://github.com/aspnet/Diagnostics/blob/9cffbd171b3f1fdd61de251685984c885e5efadb/src/Microsoft.AspNet.Diagnostics/Views/BaseView.cs#L58) and I got confused a little. It disposes the stream which is basically the response stream. 

Should this be flush instead of dispose?

**Comment by Eilon** [comment]
Should change the `StreamWriter` to `AutoFlush`.
