### ISSUE TITLE
Pkg rename: Microsoft.AspNet.Diagnostics.Interfaces -> Microsoft.AspNet.Diagnostics.Abstractions

### ISSUE THREAD

**Issue by muratg** [aspnet/Diagnostics#128]
See https://github.com/aspnet/Announcements/issues/8#issuecomment-97566113

**Comment by BrennanConroy** [comment]
https://github.com/aspnet/Diagnostics/commit/80b66cfde373e5f0744b5c825c4e4ae862df6125
