### ISSUE TITLE
Terms ErrorHandler and ErrorPage in method and class names are too similar

### ISSUE THREAD

**Issue by olegsych** [aspnet/Diagnostics#132]
It's hard to understand how an `ErrorHandler` is different from an `ErrorPage` by looking at the code in `Configure`. You'd have to look at the implementation of the `ErrorHandlerMiddleware` and `ErrorPageMiddleware` or their documentation to learn that first shows a static error page for external users and the second shows a dynamic error page for developers. It would be nice to clearly name the `UseErrorPage` method and the `ErrorPageMiddleware` to help developers understand what they do.

Background: We discovered the difference when investigating why request telemetry collected by Application Insights shows status code 200 with exceptions: Microsoft/ApplicationInsights-aspnet5#39. It took several investigations by three developers to catch the difference between the implementations of the `Configure` and `ConfigureDevelopment` methods.

**Comment by Eilon** [comment]
Need to come up with some names...

* `ErrorHandler`
 * Needs to say something about being specifically about exceptions
* `ErrorPage`
 * Needs to say something about being specifically about exceptions
 * Also needs to say something about being for development mode only

**Comment by Eilon** [comment]
Looks like we already had this tracked in https://github.com/aspnet/Diagnostics/issues/43
