### ISSUE TITLE
ErrorPageMiddleware does not set Response.StatusCode

### ISSUE THREAD

**Issue by olegsych** [aspnet/Diagnostics#133]
The `ErrorPageMiddleware` does not set `Response.StatusCode` to 500 when catching exceptions. This is different from the `ErrorHandlerMiddleware` which does. This breaks Application Insights request telemetry, which reports 200 when an exception is thrown by an application that uses the `ErrorPageMiddleware` (microsoft/ApplicationInsights-aspnet#39). 

Which component is responsible for setting `Reponse.StatusCode`? 
Should the `ErrorPageMiddleware` set it?
Or, should the `ConfigureDevelopment` method `UseErrorPage` _and_ `UseErrorHandler`? 

CC: @SergKanz, @abaranch
related: Microsoft/ApplicationInsights-aspnet5#39

**Comment by Tratcher** [comment]
The `ErrorPageMiddleware` does set a 500 status code for unhandled exceptions. See https://github.com/aspnet/Diagnostics/blob/dev/src/Microsoft.AspNet.Diagnostics/Views/ErrorPage.cs#L58
Do you have a sample app that reproduces the issue you saw?

**Comment by olegsych** [comment]
You're right, I can't repro it in my local environment right now. At the time I opened this issue, we were investigating it in a different environment and we didn't realize that `ErrorPageMiddleware` relies on the pages to set the status code. Why is that, by the way? It seems like the responsibility of the middleware and when implemented in pages, the same logic has to be implemented and tested for each page.

I'll try to repro the problem in the original environment.

**Comment by Tratcher** [comment]
ErrorPageMiddleware and ErrorPage (view) are tightly coupled components. They are only in separate classes / files because Razor is used to statically generate some of the code.  There's minimal rational to how much functionality is implemented in one or the other, but in this case I think you're correct, it makes sense to move the status code logic into the middleware class.
