### ISSUE TITLE
Remove ErrorPageOptions

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Diagnostics#142]
Rather than have things turned on or off individually, just turn it all on by default and remove the options.

There is one option that is non-boolean about how many lines of source code to display. Is it worth keeping options just for that?

Note that after a recent change (https://github.com/aspnet/Diagnostics/pull/140) everything is turned off by default.

**Comment by Tratcher** [comment]
@davidfowl

**Comment by henkmollema** [comment]
We could add an optional parameter to the `UseErrorPage` extension method indicating the how many lines of source code to display and let it flow to the `ErrorPageMiddleware` class.

**Comment by Tratcher** [comment]
I think we'd start by removing everything from Options exception for the `SourceCodeLineCount`. We try to avoid passing parameters directly into middleware, it can make it more difficult to add more parameters later.

**Comment by henkmollema** [comment]
Allright, I see if I can work something out.

**Comment by Tratcher** [comment]
Dup of https://github.com/aspnet/Diagnostics/issues/80
