### ISSUE TITLE
UseErrorPage null refs for specific TagHelper use-case resulting in no error page.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Diagnostics#146]
Original issue that exposed this: https://github.com/aspnet/Mvc/issues/2710. To reproduce this problem, follow the steps mentioned in the Mvc issue.

I debugged through it a bit and found that `frame.ContextCode` was `null` at the following line: https://github.com/aspnet/Diagnostics/blob/791ec1a0161d608265e155655c029bd4f2e08bf3/src/Microsoft.AspNet.Diagnostics/Views/ErrorPage.cshtml#L100.

**Comment by kichalla** [comment]
commit 191ffe17219405c6c7c9607c20ba6dd6fbdeecde
