### ISSUE TITLE
Azure Streaming Log with Trace

### ISSUE THREAD

**Issue by YZahringer** [aspnet/Diagnostics#153]
Hello,

"System.Diagnostics.Trace.TraceInformation("Test Trace);" only write in the debug output window.

This should not write in the IIS logs? This should also work with Azure Streaming Log?

**Comment by Tratcher** [comment]
This is probably in the wrong repo. AspNet/Logging might be more appropriate.

**Comment by YZahringer** [comment]
Ok, sorry, i re-create the issue in: https://github.com/aspnet/Logging/issues/218
