### ISSUE TITLE
UseErrorHandler within a "Map"ped path -> IErrorHandlerFeature always null

### ISSUE THREAD

**Issue by scabana** [aspnet/Diagnostics#166]
I am trying to get an asp.net 5 project up and running and isolate error handling within the use of 
```csharp
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    app.Map("/api/v1", v1App =>
    {
        v1App.UseErrorHandler("/error");
        v1App.UseMvc();
    });
}
```

So I have controllers that handle requests going in to the ```/api/v1/[controller]``` paths. If one of those actions throws an error, the ```/api/v1/error``` does get called but the ```Context.GetFeature<IErrorHandlerFeature>()``` always returns null. 

Within the same project, I added a root ```UseErrorHandler``` and a controller/action that threw an exception and within the root error handler, the ```Context.GetFeature<IErrorHandlerFeature>()``` would return a value with the thrown exception.

Now, the reason I want to do this is to be able to change error handling from a version to another version of my api while maintaining backwards compatibility. It would also give me the opportunity to have different error handling for different areas of the application.

**Comment by scabana** [comment]
I just tried this way and it seems to work: 
```csharp
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    app.Map("/api/v1", v1App =>
    {
        v1App.UseErrorHandler(app2 =>
        {
            app2.Run(async (a) =>
            {
                await Task.CompletedTask;
                IErrorHandlerFeature errorHandlerFeature = a.Request.HttpContext.GetFeature<IErrorHandlerFeature>();   
            });
        });
        v1App.UseMvc();
    });
}
```
So, it seems like the bug only happends if you use a controller within a ```Map```ped application.

**Comment by Tratcher** [comment]
No repro with the latest beta7 packages. What version are you using?

If it still repros then I recommend pushing a full repro project to GitHub.

**Comment by scabana** [comment]
Still on beta6 here. Should have mentionned this in the initial post. I'll close for now and re-open if I get it again. Thanks for checking!
