### ISSUE TITLE
Redirection of dll in Servicing and runtime info page data

### ISSUE THREAD

**Issue by kichalla** [aspnet/Diagnostics#172]
I was testing Servicing scenarios where I added a redirection for dnx as well as Newtonsoft.Json package's dll.

For example, my `index.txt` file content looks like this:

```
nupkg|Newtonsoft.Json|6.0.6|lib/portable-net45+wp80+win8+wpa81+aspnetcore50/Newtonsoft.Json.dll=packages/Newtonsoft.Json/6.0.7/lib/portable-net45+wp80+win8+wpa81+aspnetcore50/Newtonsoft.Json.dll
dnx|coreclr-win-x64|1.0.0-beta7=runtimes/dnx-coreclr-win-x64.1.0.0-beta7-15119
```

Currently runtime info middleware shows information like below, which ideally is not accurate as the content is coming from version 6.0.7...I do not have a solution in mind (to begin with we are not redirecting a package but a dll only) but we should try to fix this i think...
![image](https://cloud.githubusercontent.com/assets/6559784/9554575/a8b01398-4d7b-11e5-854c-25663c6b86cb.png)

FYI: it correctly displays the forwarded information of DNX 
![image](https://cloud.githubusercontent.com/assets/6559784/9554629/06583656-4d7c-11e5-892c-54a72aeddf01.png)

**Comment by Eilon** [comment]
Closing because there are no plans to implement this.
