### ISSUE TITLE
Poor diagnostics when UseErrorHandler points to a non-existing URL (IIS/IIS Express)

### ISSUE THREAD

**Issue by Eilon** [aspnet/Diagnostics#174]
My project has the usual `app.UseErrorHandler("/Home/Error");` call in it, but I forgot that I deleted the `/Home/Error` action from my app. I'm using IIS Express locally, and IIS on Azure Web Sites.

When I run locally, I get the following IIS error:

```
HTTP Error 403.14 - Forbidden

The Web server is configured to not list the contents of this directory.
```

And on Azure it behaves as if my web app never started, showing a "how to upload your site to Azure" default help page.

It would be nice if there was some way to detect this incorrect configuration of my app and show a more meaningful and actionable error. It took me, @muratg, and @anurse quite a while to figure out what was going on.

**Comment by davidfowl** [comment]
Is that beta6?

**Comment by Eilon** [comment]
May have even been beta5... I can try with newer bits.

**Comment by danroth27** [comment]
We tried this with beta7 and it looks like you now just get a 404 response for the original request, which his a bit misleading as it's the error page that cannot be found not the originally request resource. Ideally in this situation you would get a 500 because the server is misconfigured.

**Comment by danroth27** [comment]
@Tratcher Let's chat about what we can do here.

**Comment by davidfowl** [comment]
We should also try this with the HttpPlatform handler since that's our IIS story going forward.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2595
