### ISSUE TITLE
Enable skipped database error page tests on Mono

### ISSUE THREAD

**Issue by kichalla** [aspnet/Diagnostics#176]
Regarding https://github.com/aspnet/Diagnostics/commit/12d9302a31c9f83a3a7ee1165e6e760677c44efd

cc: @bricelam @davidfowl

**Comment by bricelam** [comment]
cc @natemcmaster @rowanmiller

**Comment by rowanmiller** [comment]
This is because the tests use a SQL Server database (specifically a LocalDB database). One option is to just cut them over to always use SQLite since that will work on all platforms.

**Comment by rowanmiller** [comment]
Not going to do for RC1 since it is a non-critical test issue

**Comment by Eilon** [comment]
@rowanmiller are you planning to investigate this for RC2 or should we move to 1.0.0?

**Comment by rowanmiller** [comment]
Moved to 1.0.0

**Comment by Eilon** [comment]
@rowanmiller @divega FYI I'm closing this because it's on Mono.
