### ISSUE TITLE
[Announcements] Breaking changes: UseErrorHandler & UseErrorPage extensions have been renamed

### ISSUE THREAD

**Issue by kichalla** [aspnet/Diagnostics#178]
This issue is for discussion related to the announcement: https://github.com/aspnet/Announcements/issues/63

**Comment by Bartmax** [comment]
:+1:

**Comment by PureKrome** [comment]
Excellent!

**Comment by stebet** [comment]
Makes sense. :+1:

**Comment by wmeints** [comment]
:+1: Sounds good. Especially since it doesn't work on production.

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
