### ISSUE TITLE
Publish unhandled errors to telemetry source

### ISSUE THREAD

**Issue by Eilon** [aspnet/Diagnostics#180]
Publish this:
1. Unhandled errors - wherever in there's a `catch` that doesn't rethrow (same place that stuff is logged right now, probably)
	- Need to do this in both DeveloperExceptionPage and ErrorHandler

Example in MVC: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/Actions/MvcRouteHandler.cs#L73-L78

**Comment by Eilon** [comment]
Related: https://github.com/aspnet/Hosting/issues/354

**Comment by JunTaoLuo** [comment]
Just to confirm, the only *unhandled* exception that needs to be written to telemetry is at [DevelopperExceptionPageMiddleware.cs#L86](https://github.com/aspnet/Diagnostics/blob/dev/src/Microsoft.AspNet.Diagnostics/DeveloperExceptionPage/DeveloperExceptionPageMiddleware.cs#L86) where we just create an exception page. All other instance of `Invoke` in  [DevelopperExceptionPageMiddleware.cs](https://github.com/aspnet/Diagnostics/blob/dev/src/Microsoft.AspNet.Diagnostics/DeveloperExceptionPage/DeveloperExceptionPageMiddleware.cs#L68-95) will end up throwing an exception that bubbles up to hosting.

Similarly [ExceptionHandlerMiddleware.cs](https://github.com/aspnet/Diagnostics/blob/dev/src/Microsoft.AspNet.Diagnostics/ExceptionHandler/ExceptionHandlerMiddleware.cs#L35-79)  will throw unhandled exceptions up to hosting or handle it at [ExceptionHandlerMiddleware.cs#L65](https://github.com/aspnet/Diagnostics/blob/dev/src/Microsoft.AspNet.Diagnostics/ExceptionHandler/ExceptionHandlerMiddleware.cs#L65)

cc @Tratcher @Eilon

**Comment by Tratcher** [comment]
Correct, you only need telemetry for app exceptions that are not re-thrown.
