### ISSUE TITLE
Consider moving DatabaseErrorPageOptions to Microsoft.AspNet.Builder namespace

### ISSUE THREAD

**Issue by Eilon** [aspnet/Diagnostics#184]
There's a general pattern where types that are used *only* for configuring middleware also end up in the `Microsoft.AspNet.Builder` namespace, alongside the various `app.UseXyz(...)` extension methods.

The `DatabaseErrorPageOptions` is used only in middleware setup (and effectively internally elsewhere), so it should move to the `Microsoft.AspNet.Builder` namespace.

The end result is that fewer namespaces need to be imported in a typical `Startup.cs` file.

**Comment by Eilon** [comment]
Just discussed another option with @Tratcher that both of us like:

Instead of passing in a particular type, the `UseXyz()` method to add the middleware could use a builder pattern and take in options that are configured inline, removing the need to reference any type by name at all, e.g.:

```c#
app.UseDatabaseErrorPage(options => {
    options.ShowExceptionDetails = true;
    options.ListMigrations = true;
});
```

Or if that's too verbose, could add a helper:

```c#
app.UseDatabaseErrorPage(options => {
    options.EnableAll(); // just sets all the properties to true
});
```

This would be even *more* inline with how other middleware works, as seen here: https://github.com/aspnet/MusicStore/blob/dev/src/MusicStore/Startup.cs#L161-L218

**Comment by Eilon** [comment]
@rynowak FYI

**Comment by rowanmiller** [comment]
Agreed on the builder pattern. I working on #190 at the moment so I will enable this pattern at the same time.

**Comment by Eilon** [comment]
@rowanmiller cool.

**Comment by rowanmiller** [comment]
Fixed in https://github.com/aspnet/Diagnostics/commit/1c26436041648a36dc6c7ff4fc346fb4c2411de3

**Comment by Eilon** [comment]
@rowanmiller remember to mark completed bugs as `3 - Done`.

**Comment by rowanmiller** [comment]
@Eilon done... I mean `3 - Done`

**Comment by Eilon** [comment]
`4 - Thanks`!
