### ISSUE TITLE
Developer exception tab for 'cookies' shows 'System.String[]' for every cookie

### ISSUE THREAD

**Issue by Eilon** [aspnet/Diagnostics#186]
I want mah cookies!

![cookies](https://cloud.githubusercontent.com/assets/202643/10269147/be6588de-6a82-11e5-950e-6817b0c8a0f9.png)

Not arrays!

![arrays](https://cloud.githubusercontent.com/assets/202643/10269146/bc12b17e-6a82-11e5-8e08-dfb96dc09d38.png)

Probably need to check if the cookie is an array and show a line for each item?

**Comment by Tratcher** [comment]
https://github.com/aspnet/Diagnostics/issues/162

**Comment by Eilon** [comment]
Ok duh, thanks :smile: My app is on beta7, I guess I should upgrade!

**Comment by Eilon** [comment]
And I made that picture for nothing :frowning:
