### ISSUE TITLE
ExceptionHandlerMiddleware on static file returns 404

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Diagnostics#199]
```
app.UseExceptionHandler("/error.html");
```
returns 404.

Browse to `locahost:port/error.html` the file is found and displayed.

Using an Mvc route instead of an static html page, it works.

I would really like to use a static html page, but couldn't find a way to do that.

**Comment by Tratcher** [comment]
Please share your startup class.

**Comment by Bartmax** [comment]
Thank you! as soon as you asked for my startup class I noticed the ErrorHandlerMiddleware wasn't the first middleware on the pipeline.

```
public void Configure(IApplicationBuilder app) {
    app.UseIISPlatformHandler();
    app.UseStaticFiles();
    app.UseIdentity();
    var facebookConfiguration = Configuration.Get<FacebookAuthentication>("Authentication:Facebook");
    app.UseFacebookAuthentication(options => {
        options.Scope.Add("email");
        options.AppId = facebookConfiguration.ApplicationId;
        options.AppSecret = facebookConfiguration.ApplicationSecret;
    });
    app.UseExceptionHandler("/error.html");
    app.UseMvcWithDefaultRoute();
}
```

not sure why it returns a 404 in that scenario. Moving the `app.UseExceptionHandler("/error.html");` to be the first middleware works...

feel free to close the issue.

**Comment by Tratcher** [comment]
You need to put UseExceptionHandler before UseStaticFiles if you want to serve static files for error pages, it re-executes the request.

**Comment by Bartmax** [comment]
:+1: thank you
