### ISSUE TITLE
Clicking on show raw stack trace causes page to scroll back to the top

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Diagnostics#203]
![nimbus-record-video](https://cloud.githubusercontent.com/assets/174281/11007535/62ed0dee-847f-11e5-956d-561e03113a83.gif)

**Comment by pranavkm** [comment]
cc @ryanbrandenburg

**Comment by Eilon** [comment]
Probably needs a `return false;` from whatever JavaScript code there is.

**Comment by pranavkm** [comment]
> return false
Eww. Needs to do `event.preventDefault()`

**Comment by Eilon** [comment]
What about NCSA Mosaic 3.0???

**Comment by ryanbrandenburg** [comment]
Fixed in #204
