### ISSUE TITLE
Use plain JavaScript for error page.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Diagnostics#205]
Right now we have some hybrid jQuery like patterns going on in our error pages. This is extremely misleading and may eventually result in a bug. What we do isn't crazy JavaScript, therefore we shouldn't be doing the craziness that we do already.

**Comment by Eilon** [comment]
Yeah I think that's all that's needed here: if it's not jQuery, don't use `$`.

**Comment by NTaylorMullen** [comment]
That was definitely part of it. We're not doing anything complex though. There's no reason for us to even be including a minimal library to do simple things. Might as well do raw JavaScript.

**Comment by ryanbrandenburg** [comment]
Fixed in #209
