### ISSUE TITLE
Elm: error mail

### ISSUE THREAD

**Issue by Painyjames** [aspnet/Diagnostics#208]
I was wondering if it would be possible to have something in place to deal with error emails.
It could be a delegate to implement on the startup or something of the sort.

```
services.ConfigureElm(elmOptions =>
			{
			elmOptions.OnErrorEmail = (ex, args) => emailPlatform.SendEmail());
            });
```

And then having ```ElmLogger ``` to call OnErrorEmail if it's assigned.

**Comment by Eilon** [comment]
ELM is only about having a page on the site for an admin or developer to see recent log entries. It's not about reporting errors via email.

**Comment by Painyjames** [comment]
Oh I see.
Started working on a place that is using it and it seemed that was a replacement for Elmah, so I assumed that functionality could be part of the project.

Closing the issue now.
