### ISSUE TITLE
AnalysisBuilder.Build may add duplicate middleware if called more than once

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Diagnostics#213]
https://github.com/aspnet/Diagnostics/pull/207#discussion_r45774856

"We don't ever call build twice though, and worst case you end up with some duplicate events.
This Build is also only ever called on branches that have first called New (e.g. Map).
Would you prefer an InvalidOperationException if it's called twice? That seems worse than a duplicate EndOfPipeline event.
I don't think we can do anything else but change from wrapping the inner builder to completely replacing it."

**Comment by Eilon** [comment]
@Tratcher @davidfowl how strongly do you feel about this issue?

**Comment by Tratcher** [comment]
Meh, we just filed it for future reference.

**Comment by Eilon** [comment]
Backlog then. Thanks!

**Comment by Eilon** [comment]
Closing due to lack of demand.
