### ISSUE TITLE
Add Html formpost values to the error page

### ISSUE THREAD

**Issue by Anderman** [aspnet/Diagnostics#218]
### feature requests

It will be nice to see the posted values of a form post

**Comment by Eilon** [comment]
Form post values can be quite huge, so we'd have to consider how much data to show (we can't always show all of it - it might be binary data anyway).

It also involves reading the form (obviously!), which is generally a one-shot deal, so that might not always even work.

**Comment by Tratcher** [comment]
The form is cached by default.

**Comment by Eilon** [comment]
Yeah just need to be careful in the cases when the form isn't cached.

**Comment by Eilon** [comment]
Closing because there are no plans to implement this.
