### ISSUE TITLE
Move ICompilationException to Diagnostics.Abstractions

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Diagnostics#220]
We use `ICompilationException` as a contract between diagnostics and other middlewares (primarily Mvc) that perform runtime compilation to show a pretty printed compilation failure. Currently the contract for this exception is located in `Microsoft.Extensions.CompilationAbstractions`. This would allow removing the CompilationAbstractions dependency.

**Comment by davidfowl** [comment]
It also means that hosting will end up depending on this weird assembly :smile:

**Comment by pranavkm** [comment]
Why would hosting need to depend on this assembly?

**Comment by Tratcher** [comment]
Oh, it's used here for the startup exception page: https://github.com/aspnet/Hosting/blob/5bb737b6ad24edb8d9f77aa3b48b17b24b4dfc0d/src/Microsoft.AspNet.Hosting/Startup/StartupExceptionPage.cs#L54

**Comment by pranavkm** [comment]
That's meant for compile time exceptions (stuff coming from DNX) which we can leave as is. This was specifically for runtime compilation.

**Comment by davidfowl** [comment]
Assigned to you @pranavkm. You'll have to leave a copy in DNX so that nothing breaks.

**Comment by pranavkm** [comment]
Yeah - I'm going to rename the namespace for this interface so the current one can co-exist until we transition. For https://github.com/aspnet/Hosting/issues/510, are we simply gutting the code?
