### ISSUE TITLE
Remove RuntimeInfoMiddleware dependency on ILibraryManager by removing the list of packages

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Diagnostics#233]
We need to update the `RuntimeInfo` middleware in this repo after https://github.com/aspnet/Hosting/issues/514 removed platform services like ILibraryManager.

**Comment by davidfowl** [comment]
We should just remove the package display.

**Comment by JunTaoLuo** [comment]
Also clean up `UseRuntimeInfoPage` to use `app.UseMiddleware<RuntimeInfoMiddleware>(options)` instead.

**Comment by Eilon** [comment]
@davidfowl I'm fine with not showing packages, but showing the DLLs is still important. What's the right way to get the list of loaded DLLs?

**Comment by davidfowl** [comment]
There's no way to do that right now. There's a corefx issue I've been pushing but no progress yet.

**Comment by Eilon** [comment]
Ok so for this item we'll just remove the package list, and I'll log a new bug to add the loaded DLL list instead.

Do you have a link to the CoreFX bug?

**Comment by Eilon** [comment]
Here's the bug to list loaded DLLs in the info page: https://github.com/aspnet/Diagnostics/issues/237
