### ISSUE TITLE
Diagnostics should register encoders in startup or use default values all the time

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Diagnostics#234]
See here - https://github.com/aspnet/Diagnostics/blob/dev/src/Microsoft.AspNet.Diagnostics/Views/BaseView.cs#L69 where the body of the extension method is:

```C#
public static HtmlEncoder GetHtmlEncoder(this IServiceProvider serviceProvider)
{
    return (HtmlEncoder)serviceProvider?.GetService(typeof(HtmlEncoder)) ?? HtmlEncoder.Default;
}
```

We should either require registering encoders in the service container or use `*Encoder.Default` all the time. I'd prefer the latter since these are diagnostic pages and are not meant for production views.

**Comment by Eilon** [comment]
I'm fine just using the default everywhere in these.
