### ISSUE TITLE
RuntimeInfoMiddleware should list the loaded DLLs

### ISSUE THREAD

**Issue by Eilon** [aspnet/Diagnostics#237]
In https://github.com/aspnet/Diagnostics/issues/233 we removed the list of packages from the page, but we should add back a similar list but for the list of loaded DLLs (and their locations, versions, etc.).

This is blocked on a CoreFX issue.

**Comment by ryanbrandenburg** [comment]
Which CoreFX issue so I know when I'm freed?

**Comment by Eilon** [comment]
@davidfowl what's the CoreFX issue from https://github.com/aspnet/Diagnostics/issues/233#issuecomment-168092277 ?

**Comment by ryanbrandenburg** [comment]
@davidfowl bump for that issue number so I'll know when I can proceed.

**Comment by Eilon** [comment]
Moving to backlog.

**Comment by mikeharder** [comment]
I think this is the CoreFX issue tracking `GetAssemblies()`, but this API seems to be rejected for 1.0.0.  https://github.com/dotnet/corefx/issues/1784

**Comment by davidfowl** [comment]
@Eilon Can we close this?

**Comment by Eilon** [comment]
@davidfowl depends on whether we ever bring back the RuntimeInfo middleware. It was kind of neat, but we removed it because it had too many problems.

**Comment by davidfowl** [comment]
Can we keep it dead? It's pretty useless...

**Comment by Eilon** [comment]
Yeah I guess. I don't recall anyone actually missing it.

**Comment by Eilon** [comment]
Closed a bunch of related bugs:

* https://github.com/aspnet/Diagnostics/issues/285
* https://github.com/aspnet/Diagnostics/issues/280
* https://github.com/aspnet/Diagnostics/issues/286
* https://github.com/aspnet/Diagnostics/issues/287
