### ISSUE TITLE
Microsoft.AspNet.Diagnostics.Elm Not Seeing Scope or Message

### ISSUE THREAD

**Issue by jmzagorski** [aspnet/Diagnostics#242]
I copied the ElmPageSample from https://github.com/aspnet/Diagnostics/tree/c536b339d0be51429e72a3bee2f00ddb88ec68b9/samples/ElmPageSample and also tried to implement this in one of my MVC6 applications exactly as you had Elm configured in your sample. However, I never see the scope name or the message/Exception from the capture page. I am able to navigate to the CapturePage and I can see the http info such as cookies/status code etc, but not the all important error message and exception. It looks like there is a table structure below the Filter search but there is nothing there. Thank you for any assistance you can give.

**Comment by Eilon** [comment]
@jmzagorski at this time the ELM feature is not being actively worked on so I'm putting this bug in the backlog.

**Comment by jmzagorski** [comment]
thanks for the reply. I found that serilog worked for the time being even though it lacks an already developed capture page from what I could tell.
