### ISSUE TITLE
Disable `FunctionalTests.DatabaseErrorPageSampleTest.DatabaseErrorPage_ShowsError`...

### ISSUE THREAD

**Issue by dougbu** [aspnet/Diagnostics#251]
...  on non-Windows or fix it to run xplat.

Currently hits "System.PlatformNotSupportedException: Integrated Security is not supported on non-Windows platform." errors rather than the expected issues.

On a related note, strongly suggest adding `--quiet` to the `script` in this repo's `.travis.yml` file. The expected log is far too long for Travis to display.

**Comment by dougbu** [comment]
Self-assigning

**Comment by dougbu** [comment]
af97bcd (got offline squirrel from @ryanbrandenburg)

**Comment by BrennanConroy** [comment]
Download the log, you're making future peoples lives more painful by adding --quiet

**Comment by dougbu** [comment]
What useful information does `--quiet` mask? It should be the default.
