### ISSUE TITLE
Source code no longer expands/collapses

### ISSUE THREAD

**Issue by lodejard** [aspnet/Diagnostics#264]
Clicking error no longer expands.

Html still has extra lines in the html, looks like javascript is busted

![errorpage](https://cloud.githubusercontent.com/assets/1693989/14374024/c954386a-fd05-11e5-91b9-5224801cc8be.png)

**Comment by lodejard** [comment]
Looks like the bug is here
```
    function frame(el) {
        ns(el).children(".source .collapsible").toggle();
    }
```

maybe should be something like
```
    function frame(el) {
        ns(".source .collapsible", el).toggle();
    }
```

**Comment by davidfowl** [comment]
@ryanbrandenburg didn't you fix this?

**Comment by ryanbrandenburg** [comment]
I fixed the collapse/expand on the exception details. I didn't even remember/know that the code was supposed to expand. #266 has a fix.

**Comment by Tratcher** [comment]
Reactivating as this does not appear to be fixed in the RC2 release branch.

**Comment by Tratcher** [comment]
Nevermind, it was only fixed in dev.
