### ISSUE TITLE
UseStatusCodePagesWithReExecute should be able to take a query string

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Diagnostics#268]
Currently if you pass a query string on pathFormat like "/Errors/Index?id={0}" it won't work, and will prevent the route from resolving (because we're setting the formatted string directly onto HttpContext.Request.Path, where query string should already be broken off).

We should consider adding the capability to pass query strings to this function, perhaps as a "queryFormat" parameter.

CC @Eilon, @Tratcher

**Comment by ryanbrandenburg** [comment]
Doing this means we'll also have to do #267 to ensure the original query string is preserved.

**Comment by drewlsvern** [comment]
What value is queryFormat supposed to be? I can't find any documentation on this. 

Any help would be appreciated.

**Comment by Tratcher** [comment]
@drewlsvern see this sample in the test: https://github.com/aspnet/Diagnostics/pull/276/files#diff-cdde232dfc093c600857f42a907fd478R244
