### ISSUE TITLE
DNX branding shows up in the ErrorPage

### ISSUE THREAD

**Issue by rustd** [aspnet/Diagnostics#271]
**Repro Steps:**

- Create an ASP.NET Core Web App
- Introduce a compilation error
- Run the app to see the error page

**Expected:**
DNX branding should not show up in the error page. It does at the bottom as shown in this screenshot

![errorpage](https://cloud.githubusercontent.com/assets/1132652/14721455/4cbca222-07bb-11e6-85a7-5fd8fd891cc9.PNG)

**Comment by Eilon** [comment]
Hmm I don't see this in the latest packages. I ran from source code and there's no footer at all. I also don't see this being generated by searching the repo. I also looked over the last month or two of changes and didn't see where the might have been removed.

@Tratcher @ryanbrandenburg do you guys recall removing this? Or is it coming from somewhere else?

**Comment by Tratcher** [comment]
That's Hosting's startup exception page, not the developer error page:
https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/Startup/StartupExceptionPage.cs
https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/compiler/resources/GenericError_Footer.html

**Comment by rustd** [comment]
I am seeing this with this version  1.0.0-rc2-20581

**Comment by muratg** [comment]
This issue was moved to aspnet/Hosting#722

**Comment by Eilon** [comment]
Ah, nice 😄
