### ISSUE TITLE
RC2 UseStatusCodePagesWithReExecute not working

### ISSUE THREAD

**Issue by DreamingDevs** [aspnet/Diagnostics#275]
I am using `RC2-20222` with `net451 `in `VS Community 2015 Update 2`. I want to capture all 404 requests for static files and endpoints. I used `UseStatusCodePagesWithReExecute ` to capture all 404 requests.

I have following in `Configure `method of startup.cs.
```
app.UseDefaultFiles();
app.UseStaticFiles();
app.UseStatusCodePagesWithReExecute("/Error/HttpError/{0}");
// lines omitted for brevity
 app.Use((context, next) =>
{
          context.Response.StatusCode = 404;
          return next();
 });
```

Action method - 

```
        [HttpGet("HttpError/{errCode}")]
        public async Task<IActionResult> HttpError(string errCode)
        {
            var logId = Guid.NewGuid();
            // some await business operation
            var response = new ErrorResponse()
            {
                Message = "Something went wrong",
                ErrorId = logId
            };
            
            return BadRequest(response);           
        }
```

But now nothing happens, I mean I kept a break point at action method, it doesn't get hit.

I need to handle Static file 404's along with end points 404's.

**Comment by davidfowl** [comment]
Where is the UseMvc call?

**Comment by DreamingDevs** [comment]
I have the UseMvc call, I removed that line for brevity.

I figured out the problem, I have a conditional redirect middleware which is not letting the call go to the mentioned controller action.

Sorry for inconvenience. I am closing the issue.
