### ISSUE TITLE
Enviroment tab in error page middleware

### ISSUE THREAD

**Issue by Praburaj** [aspnet/Diagnostics#28]
This error page middleware is a port of the katana error page middleware where OWIN environment existed. So we had a Environment tab in the error page output listing all the environment variables. In Aspnet vNext there is no environment but we have features. 

What do we do with this `Environment` tab in the error page. Options
1. Remove it as it not relevant any more
2. Provide any other information like features - Will that be any useful for developer?

**Comment by Tratcher** [comment]
Just remove the tab.
