### ISSUE TITLE
Status Code Page should omit semicolon when reason phrase is unknown

### ISSUE THREAD

**Issue by rynowak** [aspnet/Diagnostics#282]
Normally the output looks like `Status Code: 400; Bad Request`

But sometimes the reason phrase isn't known like `Status Code: 541;`

We should just leave off the semicolon when that happens

**Comment by Eilon** [comment]
@rynowak @Tratcher any guess on whether this is "bad"? Is it just "ugly"?

**Comment by rynowak** [comment]
~~good~~ ~~bad~~ - nope just ugly

**Comment by Eilon** [comment]
@rynowak ok thanks!
