### ISSUE TITLE
UseRuntimeInfo has no intellisense docs

### ISSUE THREAD

**Issue by rynowak** [aspnet/Diagnostics#285]
See: https://github.com/aspnet/Diagnostics/blob/dev/src/Microsoft.AspNetCore.Diagnostics/RuntimeInfo/RuntimeInfoExtensions.cs

**Comment by Eilon** [comment]
RuntimeInfo is being removed from 1.0.0 in https://github.com/aspnet/Diagnostics/issues/279, but we'll add it back post-v1 in https://github.com/aspnet/Diagnostics/issues/280.

**Comment by Eilon** [comment]
Closing because there are no current plans to bring this feature back.
