### ISSUE TITLE
RuntimeInfo displays 4.0.0.0 for runtime version on CoreCLR

### ISSUE THREAD

**Issue by rynowak** [aspnet/Diagnostics#286]
Was hoping for the version of dotnet/corefx, and I just get `4.0.0.0`

Output:

```
Environment:

Operating System: Windows

Runtime Version: 4.0.0.0

Runtime Architecture: x64

Runtime Type: CoreCLR
```

**Comment by Eilon** [comment]
RuntimeInfo is being removed from 1.0.0 in https://github.com/aspnet/Diagnostics/issues/279, but we'll add it back post-v1 in https://github.com/aspnet/Diagnostics/issues/280.

**Comment by Eilon** [comment]
Closing because there are no current plans to bring this feature back.
