### ISSUE TITLE
RuntimeInfo include of css not processed

### ISSUE THREAD

**Issue by rynowak** [aspnet/Diagnostics#287]
```
<style>
        <%$ include: RuntimeInfoPage.css % >
    </style>
```

This appears in the `<head>` instead of the actual css, so the styles aren't getting applied.

**Comment by Eilon** [comment]
RuntimeInfo is being removed from 1.0.0 in https://github.com/aspnet/Diagnostics/issues/279, but we'll add it back post-v1 in https://github.com/aspnet/Diagnostics/issues/280.

**Comment by Eilon** [comment]
Closing because there are no current plans to bring this feature back.
