### ISSUE TITLE
DeveloperExceptionPage needs better text spacing on OSX/Safari

### ISSUE THREAD

**Issue by rynowak** [aspnet/Diagnostics#288]
![image](https://cloud.githubusercontent.com/assets/1430011/15082340/15e3239e-137c-11e6-8807-edaf1d0bf011.png)

**Comment by Eilon** [comment]
@kichalla when figuring this out, if it turns out we just have "too much" CSS then consider dramatically simplifying CSS. It could be that we went overboard at some early point and added complex styles that just don't work well.

**Comment by rynowak** [comment]
This is also the case on Edge

![image](https://cloud.githubusercontent.com/assets/1430011/16096291/19b3737a-32fd-11e6-886f-a47fec758876.png)
