### ISSUE TITLE
Finding Original RequestUri with IExceptionHandlerFeature

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Diagnostics#292]
_From @shawnwildermuth on May 12, 2016 19:42_

I'm trying to log the request URI when an exception is thrown. Logging is too abstracted out to do it so I thought that IHttpRequestFeature was my trick. Here's what I'm trying, please let me know if I'm way off the right track:

First I'm using an exception page:

```
app.UseExceptionPage("/Exception");
```

This logs the exception, but just the bare exception, no state of the request.

So, inside the Action for /Exception, I'm doing this:

```
    [HttpGet("Exception")]
    public IActionResult Exception()
    {
      var exception = HttpContext.Features.Get<IExceptionHandlerFeature>();
      var request = HttpContext.Features.Get<IHttpRequestFeature>();

      if (exception != null && request != null)
      {
        var originalPath = request.Path;
        // I could cast the request object to a Frame to get at the information, but that feels dirty

        // Manually logging the information
      }

      return View();
    }
```

_Copied from original issue: aspnet/HttpAbstractions#630_

**Comment by Tratcher** [comment]
We should add the original path to IExceptionHandlerFeature here:
https://github.com/aspnet/Diagnostics/blob/0a444088c9a7c5c6b4073c92104b48af734ef523/src/Microsoft.AspNetCore.Diagnostics/ExceptionHandler/ExceptionHandlerMiddleware.cs#L66

**Comment by bedwar2** [comment]
When a 403 is encountered I'd like to get the RequestURI to log what URL user attempted.  Shouldn't ReuestURI be on the IHTTPRequestFeature in that case as well?  I see the original request was for it to be on IHttpRequestFeature.  I still think it should be there.  I use app.UseStatusCodePagesWithReExecute.

**Comment by Tratcher** [comment]
@Eilon are the versioning guildlines ready for v1.1? Do they allow adding properties to feature interfaces?

**Comment by Eilon** [comment]
@Tratcher working on the guidelines. Changing an interface in any way is a breaking change that we would not make. We can add a new interface, though.
