### ISSUE TITLE
Exceptions during razor views rendering don't show the source line

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Diagnostics#293]
Can repro in a new WebApp from template. 

Repro:
- Update `Index.cshtml` with `@(((string)null).ToString()`

Result:
![image](https://cloud.githubusercontent.com/assets/1165805/15341324/dcf4f06a-1c42-11e6-80c2-5b80241529c6.png)

Expected:
It should display the line number where the exception occurred.

NB:
- Looking at the `sourceTree` value the line numbers are generated in the razor source.
- This scenario should be added in release checks

**Comment by pranavkm** [comment]
Seems like an issue with compiling using the `PortablePdb` switch. I asked the Roslyn folks at https://github.com/dotnet/roslyn/issues/11535 for guidance on this.

**Comment by pranavkm** [comment]
The issue's been fixed for RTM - https://github.com/dotnet/coreclr/issues/3906. We're working on picking up the packages now so this is likely to get fixed soon. I filed https://github.com/aspnet/Mvc/issues/4737 to add a functional test to verify this behavior is covered.

**Comment by pranavkm** [comment]
The RC3 packages fix this issue in netcoreapp, but it's broken on desktop. I guess we could generate full pdbs if the right components are present. @davidfowl, does that sound ok?

**Comment by dougbu** [comment]
@pranavkm why is dotnet/coreclr#3906 considered closed if the problem is only fixed when using .NET core? Have you filed a CoreFx bug for full desktop support?

**Comment by pranavkm** [comment]
@davidfowl's going to commonize the pdb reader (https://github.com/aspnet/Diagnostics/pull/300) and use it in Hosting and Diagnostics. I'll check in the test part of https://github.com/aspnet/Mvc/commit/73ddec7c67d7de15cdee91163c0d4078904274f6 once this is done to get some e2e coverage.
