### ISSUE TITLE
Exception Page showing only method names in the callstack

### ISSUE THREAD

**Issue by rynowak** [aspnet/Diagnostics#304]
![image](https://cloud.githubusercontent.com/assets/1430011/16101353/b6987da4-3319-11e6-9cdd-7a5dab7e3201.png)

Using:
dotnet 1.0.0-preview2-003024
Microsoft.Extensions.Diagnostics 1.0.0-rc3-21343

**Comment by lodejard** [comment]
+1 

I was just going to file this - it looks like it changed behavior when the stack helper class was used instead of text parsing.

This would be great to fix - it makes the stack kind of silly looking and not useful

**Comment by Eilon** [comment]
Yeah this is bad, but not escrow resetting. The "Raw exception details" does show the well-formatted info.

**Comment by pranavkm** [comment]
I have the PR ready for this (https://github.com/aspnet/Diagnostics/issues/306) in case we plan on taking this for 1.0.0.
