### ISSUE TITLE
ELM Details page makes Assumptions about requests that may not be true

### ISSUE THREAD

**Issue by SamuelEnglard** [aspnet/Diagnostics#307]
The Details page assumes that all requests have a Content-Type, and while generally true this is not guaranteed. This assumptions causes it to crash when loading on such a request. While I haven't looked I'm willing to bet it makes other assumptions.

(https://github.com/aspnet/Diagnostics/blob/dev/src/Microsoft.AspNetCore.Diagnostics.Elm/Views/DetailsPage.cs#L191)

**Comment by Eilon** [comment]
@SamuelEnglard thanks for the bug report. The ELM feature is currently still in "prototype" stage so we're not actively fixing bugs in it. However, I've marked the bug as up-for-grabs in case anyone wants to take a try at fixing it.
