### ISSUE TITLE
UseStatusCodePagesWithReExecute is not preserving status code.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Diagnostics#308]
If I use the `StatusCodePages` middleware with ReExecute
```
app.UseStatusCodePagesWithReExecute("/error.html");
```

According to [documentation](https://docs.asp.net/en/latest/fundamentals/error-handling.html#configuring-status-code-pages) it should preserve status code.

>The UseStatusCodePagesWithReExecute method will still return the original status code to the browser, but will also execute the handler given at the path specified.

In this case, the reexecute is done but the response is 200 (handled by static files middleware).

What am I missing?

**Comment by Bartmax** [comment]
I think the staticfiles middleware is resetting the error code to 200. That can be the issue here?

**Comment by Tratcher** [comment]
Yes, this is a known issue. cc @glennc 

StaticFiles also does several other things not quite appropriate for some status codes like processing etags and setting cache headers.

It may be more appropriate to send these requests to an MVC route and serve the files using FileResult. This should preserve the status code and not add any caching headers.

**Comment by Bartmax** [comment]
Ok, I'll do that! Thanks.
