### ISSUE TITLE
app.UseStatusCodePagesWithReExecute("/ErrorHandler/StatusCode{0}") not handling 400 errors

### ISSUE THREAD

**Issue by bedwar2** [aspnet/Diagnostics#310]
400 errors are not being redirected to the controller using app.UseStatusCodePagesWithReExecute("/ErrorHandler/StatusCode{0}")

It is working for 403 and 404.   Tried testing with 400 by adding a "%" into the URL.   Just getting a generic 400 page in Chrome and Firefox and a pop-up window in IE.  Checking network in Developer Tools response is coming from web server.

Should have gone to StatusCode400 action of my ErrorHandler controller.

Duplicated by running in VS 2015 in Debug mode (using IIS Express)

**Comment by Tratcher** [comment]
That's not going to work. IIS/Express is rejecting that request before it even surfaces it to the application, so there's nothing the application can do to handle it.

**Comment by bedwar2** [comment]
Ok Thanks, now I just need to try and figure out how to generate a 400 error the app handles.
