### ISSUE TITLE
Add EF Migration status page without Error page

### ISSUE THREAD

**Issue by pherbel** [aspnet/Diagnostics#314]
Would be great a new page where I can see the database and I can see the status of the migrations like on the error page.

It could be very helpful in development time to use this page and I can apply the migration if I want.

**Comment by Eilon** [comment]
@rowanmiller can you have a look?

**Comment by rowanmiller** [comment]
Agreed that this would be useful, the initial prototype of the database error page was actually more of a status page. It's lower priority than a number of other EF features, so popping on the backlog for the moment. This would also be a really great candidate for a third party library/project if anyone in the community wanted to take it on before we are ready.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2592
