### ISSUE TITLE
The action is always forwarded by .UseExceptionHandler(path)

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Diagnostics#320]
@ajaybhargavb @pranavkm @NTaylorMullen I have an app that accepts a number of actions ... GET's, PUT's, POST's, etc. If I use a Url that doesn't match a route for a PUT request,  `.UseExceptionHandler(path)` wasn't tossing back my error view ...
```
dbug: Microsoft.AspNetCore.Routing.Tree.TreeRouter[1]
Request successfully matched the route with name '' and template 'error/{v?}/{y?}'.
dbug: Microsoft.AspNetCore.Mvc.Internal.ActionSelector[2]
Action 'myapp.ErrorController.Index (myapp)' with id 'e5866f74-727c-4204-9870-187857a04836'
did not match the constraint 'Microsoft.AspNetCore.Mvc.Internal.HttpMethodActionConstraint'
dbug: Microsoft.AspNetCore.Mvc.Internal.MvcAttributeRouteHandler[3]
No actions matched the current request
```
... then I realized that Diagnostics is forwarding the action (i.e., it's trying to match the `HttpMethodActionConstraint` for the View, which in this case was a PUT to the error view).

Going from ...
```c#
[HttpGet("/error/{v?}/{y?}")]
public IActionResult Index(string v, string y)
{ ... }
```
... to ...
```c#
[HttpGet, HttpPut, HttpPost, HttpDelete, HttpPatch]
[Route("/error/{v?}/{y?}")]
public IActionResult Index(string v, string y)
{ ... }
```
... solved the issue.

This behavior of passing on the action to the path in `.UseExceptionHandler(path)` is apparently by-design, so I think this is a documentation issue. Before I open a Docs repo issue, can you verify this is the correct behavior for `.UseExceptionHandler(path)`? A PUT goes bad, `path` will get a PUT. A DELETE goes bad, `path` will get a DELETE ... etc.

**Comment by kichalla** [comment]
Yeah, that seems like an expected behavior and probably should be documented. The workaround you have is good but it should also work with just the `Route` attribute and no method constraints decorated. 

From the following code, it appears that the any other properties apart of Path is not modified, so this is an expected behavior:
https://github.com/aspnet/Diagnostics/blob/1.0.0/src/Microsoft.AspNetCore.Diagnostics/ExceptionHandler/ExceptionHandlerMiddleware.cs#L40

**Comment by GuardRex** [comment]
@kichalla Yes, @tuespetre just called me a moron on Slack for not just dropping the actions! lol ... Well, he put it very nicely, of course.

Ok, I'll close here and open in Docs in a sec and cross-link the issues.

Thanks! :smile:
