### ISSUE TITLE
Diagnostics middleware no longer has a way to expand the source for compilation errors

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Diagnostics#324]
There are two separate error pages - one for compilation failures and one for all other exceptions which share the same css and js. In changing the layout for the regular exception page, we've lost the ability to expand \ collapse nodes for the compilation error page. E.g.

![image](https://cloud.githubusercontent.com/assets/174281/17383897/4d49d916-598d-11e6-95fb-646b8a3c34c3.png)

**Comment by pranavkm** [comment]
cc @kichalla

**Comment by kichalla** [comment]
I am looking into fixing it now.
