### ISSUE TITLE
ELM logs disappears. Can we persist it to a file or DB?

### ISSUE THREAD

**Issue by valcs007** [aspnet/Diagnostics#328]
Hi,
Since ELMAH framework is not supported for ASP.Net Core, i started using ELM prototype capturing unhandled Exceptions as well as logging. 

**Snippet:**

```
services.AddElm(options => {
            options.Path = new PathString("/elm");
            options.Filter = (name, level) => level >= LogLevel.Information;
        });
```

 app.UseElmPage(); // Shows the logs at the specified path
            app.UseElmCapture(); // Adds the ElmLoggerProvider

It allows me to view **/ELM** page where it shows all my logs but it disappears from my webserver after sometime. Where is this currently stored? Do we have a way to persist this in a file or to DB?

If you have any other suggestion, please let us know. We want to capture exceptions from PROD.

Thanks,
Valliappan

**Comment by pranavkm** [comment]
An alternative to messing with ELM would be to look at using [Serilog](https://www.nuget.org/packages/Serilog.Extensions.Logging) or [NLog](https://www.nuget.org/packages/NLog.Web.AspNetCore) to provide the serialization. You might have to use [ExceptionHandler](https://github.com/aspnet/Diagnostics/blob/dev/samples/ExceptionHandlerSample/Startup.cs) to capture and log unhandled exceptions.

ELM's storage container [`ElmStore`](https://github.com/aspnet/Diagnostics/blob/dev/src/Microsoft.AspNetCore.Diagnostics.Elm/ElmStore.cs) is registered in the service collection,, so you should have access to recorded events via DI. However you would have to come up with the infrastructure to figure out when and how to serialize this data.

**Comment by Eilon** [comment]
Right, ELM is not (currently) designed to save logs across the application restarting. For that purpose we recommend using any of the great, fully-featured logging systems out there that support storing logs to a file/database/remote store, and then use a log viewer to see what's up in those logs.
