### ISSUE TITLE
Port fix for: Exception Page showing only method names in the callstack #304

### ISSUE THREAD

**Issue by Eilon** [aspnet/Diagnostics#335]
Should port the fix for https://github.com/aspnet/Diagnostics/issues/304 to 1.0.1.

**Comment by pranavkm** [comment]
1.0.2?

**Comment by Eilon** [comment]
This package never had a 1.0.1, so this would be the first bug for that.

**Comment by Eilon** [comment]
@pranavkm this is approved for 1.0.1, please port the fix.

**Comment by pranavkm** [comment]
Fixed in https://github.com/aspnet/Diagnostics/commit/3ea89d1631a4d12f83c01438e1ac57a7eb6ee292
