### ISSUE TITLE
Getting the original requested Path when using UseStatusCodePagesWithReExecute

### ISSUE THREAD

**Issue by strohhut** [aspnet/Diagnostics#338]
When requesting `http://example.com/nonexisting`: Is it possible to get the info about the original request when an action executes because it is the handler for `UseStatusCodePagesWithReExecute`?

If not then how else can I log requested urls that have a non-OK response like 404?

**Comment by Tratcher** [comment]
See IStatusCodeReExecuteFeature in https://github.com/aspnet/Diagnostics/blob/dev/src/Microsoft.AspNetCore.Diagnostics/StatusCodePage/StatusCodePagesExtensions.cs
