### ISSUE TITLE
Preserving Querystring w/ UseStatusCodePagesWithReExecute

### ISSUE THREAD

**Issue by tysonnero** [aspnet/Diagnostics#339]
Is it possible to preserve the original querystring when using UseStatusCodePagesWithReExecute. If so, will the params stay on the url or will they be stored somewhere else? If stored somewhere else :-), how are they accessed after the fact?

Thanks!

**Comment by Tratcher** [comment]
Yes, see https://github.com/aspnet/Diagnostics/blob/3a868d87a2458fd025ca71e2538b3a72f67c7c50/src/Microsoft.AspNetCore.Diagnostics/StatusCodePage/StatusCodePagesExtensions.cs#L185-L190

**Comment by tysonnero** [comment]
@Tratcher Thanks for the quick response.

Do I have to upgrade to AspNetCore 1.1 for this? I am currently on 1.0.
And, how do you get at that OriginalQueryString from a Controller or View?

**Comment by Tratcher** [comment]
No, that's in 1.0. https://github.com/aspnet/Diagnostics/blob/1.0.0/src/Microsoft.AspNetCore.Diagnostics/StatusCodePage/StatusCodePagesExtensions.cs#L188
In an MVC controller you can call `HttpContext.Features.Get<IStatusCodeReExecuteFeature>()`

**Comment by tysonnero** [comment]
I can't seem to get at OriginalQueryString b/c it's not in the IStatusCodeReExecuteFeature interface. I'm getting compile time errors.

**Comment by Tratcher** [comment]
Ah, you found a bug. The original commit (https://github.com/aspnet/Diagnostics/commit/48b436ec8a2aa2d8ebcfc8682e85d336e217c8ce) added OriginalQueryString to StatusCodeReExecuteFeature but not to the interface IStatusCodeReExecuteFeature. You can work around this by downcasting to StatusCodeReExecuteFeature.

@muratg, as this requires a change to the interface we'll have to wait until 2.0.
