### ISSUE TITLE
Elm page: Log detail throws ArgumentNullException

### ISSUE THREAD

**Issue by Valensm** [aspnet/Diagnostics#340]
The log detail page throws: **An unhandled exception of type 'System.ArgumentNullException' occurred in System.Private.CoreLib.ni.dll**
 
To reproduce:
1. Create new solution in VS2015 for ASP .NET Core Web Application.
2. Install nuget package Microsoft.AspNetCore.Diagnostics.Elm (currently v. 0.2.0).
3. Add Elm to Startup.Configure ->
    app.UseElmCapture();
    app.UseElmPage();
4. Add Elm to Startuo.ConfigureServices ->
    services.AddElm(options =>
            {
                options.Path = new Microsoft.AspNetCore.Http.PathString("/elm");
                options.Filter = (a, logLevel) => logLevel == LogLevel.Error;
            });
5. Run the app.
6. Go to page http://localhost:port/elm. The page with logs is displayed - OK.
7. Choose a log entry and click to it to see details ->
    An unhandled exception of type 'System.ArgumentNullException' occurred in System.Private.CoreLib.ni.dll

**Comment by ivankarpey** [comment]
@Eilon Is there any workaround for this problem, since it's marked with `wontfix`
This issue reproduced for 0.3 preview 1

**Comment by Eilon** [comment]
@ivankarpey not that I know of, but if this is important to you I recommend grabbing the source code and modifying as needed. At this point we are not planning to ship ELM, so we are not planning to fix any bugs in it.
