### ISSUE TITLE
DataStoreErrorLogger behaves differently under .NETStandard1.3 vs .NET 4.5.1

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Diagnostics#342]
Has the same issue with AsyncLocal value as HttpContextAccessor as referenced in bug aspnet/HttpAbstractions#723, it needs to be static.

**Comment by Eilon** [comment]
So this: https://github.com/aspnet/Diagnostics/blob/dev/src/Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore/DataStoreErrorLogger.cs#L21

Needs to be `static`, just like https://github.com/aspnet/HttpAbstractions/pull/753/files#diff-ea251ec60f873af282ab3518b9f69124R33 ?
