### ISSUE TITLE
DeveloperExceptionPage throws when SourceFileContent is null in an ICompilationException

### ISSUE THREAD

**Issue by rynowak** [aspnet/Diagnostics#344]
I hit this case while working through some Razor issues. 

The SourceFileContent is dereferenced here: https://github.com/aspnet/Diagnostics/blob/dev/src/Microsoft.AspNetCore.Diagnostics/DeveloperExceptionPage/DeveloperExceptionPageMiddleware.cs#L138

We should probably harden this code since it's an error page.

**Comment by kichalla** [comment]
ee1cfdf41e2f9d5cf56bffb4e90a8fc59938e4ba
