### ISSUE TITLE
Update to netcoreapp2.0 when LocalDb works in netcoreapp2.0

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Diagnostics#354]
CoreFx issue: https://github.com/dotnet/corefx/issues/17166

**Comment by Eilon** [comment]
The LocalDb issue was fixed a while ago, so this shouldn't be an issue anymore.

**Comment by Eilon** [comment]
Oh actually it looks like this was already done: https://github.com/aspnet/Diagnostics/pull/355
