### ISSUE TITLE
Developer exception page 'Show raw exception details' only ever shows first set of details.

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Diagnostics#356]
Moved from https://github.com/aspnet/Mvc/issues/6035

When multiple exceptions are displayed (e.g. NullReferenceException, followed by an AggregateException) clicking on 'Show raw exception details' (the rawExceptionButton) only toggles the first block of raw exception code. Problem lies here:

```js
ns("#rawExceptionButton").click(function (event) {
        var div = document.getElementById('rawException');
        div.style.display = 'inline-block';
        div.scrollIntoView(true);
        event.preventDefault();
        event.stopPropagation();

        return false;
    });
```

**Comment by jbagga** [comment]
The actual issue had been fixed by https://github.com/aspnet/Diagnostics/commit/22492ed7526159b0e7ea00c60f117f83b86ec7ba

PR aspnet/Common#215 deals with displaying all the inner exceptions in an `AggregateException`
