### ISSUE TITLE
Define handlers for status codes with UseStatusCodePages

### ISSUE THREAD

**Issue by jchannon** [aspnet/Diagnostics#357]
In Nancy you can implement a `IStatusCodeHandler` which has CanHandle and a Handle methods. CanHandle returns a boolean that says for this statuscode I can handle it and then in the Handle it writes a response.

In UseStatusCodePages it seems to be a global filter for status codes. How do I say only execute `x` when the statuscode is `y`. Only examples I have seen is to write a Controller method that has a switch statement on the statuscode and that is very ugly. 

Is there a cleaner way of doing it? If not could we make it cleaner?

**Comment by Eilon** [comment]
Seems like an interesting idea, but no current plans to implement this.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2589
