### ISSUE TITLE
Elm crashes when displaying Trace level messages

### ISSUE THREAD

**Issue by dealdiane** [aspnet/Diagnostics#368]
Getting a "KeyNotFoundException: The given key was not present in the dictionary" exception when a log  contains LogLevel.Trace messages.

I'm on v 0.2.1 and have not tried it on 0.3.0-*.

It comes down to this line in the LogPage.cshtml not having the "Trace" key added:

```
var counts = new Dictionary<string, int>();
                                counts["Critical"] = 0;
                                counts["Error"] = 0;
                                counts["Warning"] = 0;
                                counts["Information"] = 0;
                                counts["Debug"] = 0;
```

Aside from adding a "Trace" key, a guard clause should be added as well to prevent reading of keys that's not in the dictionary. Also, would it be better to just get all values of `LogLevel` programmatically rather than hard-coding them?

**Comment by Eilon** [comment]
Hi @dealdiane , the ELM feature was one that was never officially shipped (hence the 0.x version number), so we don't plan on fixing any bugs in it at this time. However, we would be open to accepting a PR if you (or anyone) wishes to send one.
