### ISSUE TITLE
DeveloperExceptionPage does not show line numbers in stack trace

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Diagnostics#372]
Using 2.0.0-preview1 bits:
- Microsoft.AspNetCore.Diagnostics 2.0.0-preview1-24820 (via Microsoft.AspNetCore.All)
- Microsoft.NETCore.App 2.0.0-preview1-002101-00

Throw a runtime exception during request processing, e.g. in an inline middleware, in a Controller action, in a Razor view/page, and the exception page displays but the stack trace contains no line numbers:
```
System.Exception: middleware
   at RazorPagesSample.Startup.<>c.<Configure>b__8_0(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
```

**Comment by DamianEdwards** [comment]
@muratg @Eilon @pranavkm @davidfowl

**Comment by NTaylorMullen** [comment]
-_- This has been regressed so many times. We seriously need to have end-to-end functional tests validating this.

**Comment by pranavkm** [comment]
Well, apparently this is a known issue: https://github.com/aspnet/Mvc/issues/6120.

**Comment by NTaylorMullen** [comment]
Investigated this guy. Looks like there's a core clr issue with StackFrame that broke from netcoreapp1.1 => netcoreapp2.0. Filed an [issue here](https://github.com/dotnet/coreclr/issues/11378).

**Comment by Eilon** [comment]
We can keep this issue here at least to track.

**Comment by muratg** [comment]
@Eilon we keep this in preview1 or move out?

**Comment by Eilon** [comment]
Can keep it here for now until we at least find out what the conclusion is on the .NET side.

**Comment by lt72** [comment]
This should now be fixed in CoreFX with https://github.com/dotnet/corefx/pull/19364.

**Comment by Eilon** [comment]
@lt72 thanks!

**Comment by Eilon** [comment]
@NTaylorMullen - can you confirm we're seeing the right thing on the latest build of the CLI that I sent out?

**Comment by NTaylorMullen** [comment]
Verified by doing `dotnet new -t mvc` and throwing an exception in the `HomeController`:
![image](https://cloud.githubusercontent.com/assets/2008729/25876180/5cc81a78-34d0-11e7-997f-6643df492b76.png)

All looks good!

**Comment by pranavkm** [comment]
Can you unskip https://github.com/aspnet/Mvc/issues/6120?

**Comment by kichalla** [comment]
This issue resurfaced again in the mirror, probably because the corefx team merged their commits from preview1(where it regressed) to dev(where it was working when @NTaylorMullen unskipped this).

**Comment by kichalla** [comment]
This has been fixed. https://github.com/dotnet/corefx/issues/19838

**Comment by NTaylorMullen** [comment]
This has been regressed again for net461 apps. Re-opened the corefx issue: https://github.com/dotnet/corefx/issues/19838

**Comment by pranavkm** [comment]
Do we need to revive this - https://github.com/aspnet/Common/commit/31a4622223d99520bebf629ee545a7d382d50b61?

**Comment by NTaylorMullen** [comment]
Yup, opened [this](https://github.com/aspnet/Common/issues/235) issue.

To work around this issue for those watching you can add this to your csproj:

```XML
<DebugType Condition="'$(TargetFrameworkIdentifier)'=='.NETFramework'">Full</DebugType>
```

**Comment by NTaylorMullen** [comment]
Have other issues tracking the fix of this now:
- https://github.com/aspnet/Mvc/issues/6356
- https://github.com/aspnet/Common/issues/235
