### ISSUE TITLE
Wrap ILoggerFactory to add custom ILoggerProvider to any ILoggerFactory implementation

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/Diagnostics#373]
We should wrap the ILoggerFactory, or do something similar, so that Diagnostic middleware can add providers to the factory

PR where changes need to be addressed https://github.com/aspnet/Diagnostics/pull/371

**Comment by Eilon** [comment]
@ajcvickers - FYI on this, regarding EF Database error page.

**Comment by ajcvickers** [comment]
Consider switching to DiagnosticSource for this. (Note: this may not be easier, but from my understanding of ILogger verses DiagnosticSource capabilities it seems like a better fit.)

Also, I am making changes to EF logging that will affect the Database Error Page.

**Comment by Eilon** [comment]
@ajcvickers / @anpete - any concrete plans for this?

**Comment by ajcvickers** [comment]
@Eilon Andrew re-wrote this last week to use DiagnosticSource instead. Closing this.
