### ISSUE TITLE
Add support for logging HttpClient calls

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Diagnostics#384]
Register a diagnostic listener somewhere that logs outgoing http calls.

/cc @pakrym

**Comment by Eilon** [comment]
What is AppInsights doing for this? Do we need to do anything special in ASP.NET Core?

**Comment by pakrym** [comment]
@davidfowl want's HttpClient requests logged to console without involving AI. Same way we do with EF queries.

**Comment by Eilon** [comment]
Interesting. This would be a first for us - that is, to add logging to something we don't even own. We'd have to think about that a bit...
