### ISSUE TITLE
DeveloperExceptionPage should include routing details

### ISSUE THREAD

**Issue by miloush** [aspnet/Diagnostics#403]
If applicable, the exception page should have a tab with current route name, controller, action and routing values.

**Comment by davidfowl** [comment]
@rynowak is this feasible? Is the routing feature available on the outgoing or do we remove it from the request on the way out?

**Comment by Eilon** [comment]
There's also the minor problem of the Diagnostics page having access to the IRouteFeature (or whatever it's called). But if we move routing lower down the stack, that would just solve itself.

Regarding whether the routing feature is available on the outgoing, I wonder in general if it makes sense for middlesware to remove features on the way out? We've seen that sometimes cause issues in this type of error case.

**Comment by rynowak** [comment]
Yes, this is feasible.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2586
