### ISSUE TITLE
Dedicated page for JavaScript invoked on server-side

### ISSUE THREAD

**Issue by rosieks** [aspnet/Diagnostics#404]
SpaServices project provides ability to run JavaScript on server. When such invocation failed the following error is displayed.

![image](https://user-images.githubusercontent.com/1107959/29476261-7e05f9ca-8463-11e7-9e3d-fbb1cd04425c.png)

It would be nice to have dedicated page that focus on JavaScript error and provide nicefied stacktrace, current npm version, etc

**Comment by Eilon** [comment]
@SteveSandersonMS any thoughts on this? We've been thinking of some diagnostics pages extensibility in general, for example: https://github.com/aspnet/Diagnostics/issues/403

**Comment by SteveSandersonMS** [comment]
It would definitely be good to present this information more readably - the stack trace at least.

If the new diagnostics extensibility point issued a call back to get the nicely formatted error info, passing the original exception, then it would be easy enough to embed whatever info we need into the `NodeInvocationException` and pull it out.

**Comment by Eilon** [comment]
Ok, we'll consider something for 2.1.0 then.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2585
