### ISSUE TITLE
Add support for binding HealthChecks middleware to a port

### ISSUE THREAD

**Issue by anurse** [aspnet/Diagnostics#414]
This is useful for ensuring that the health checks are only visible to infrastructure components and not available on the public internet. Using a different port for health checks makes that easier to configure.

**Comment by Tratcher** [comment]
This won't work for ANCM scenarios, right?

**Comment by anurse** [comment]
Correct. But it's implementation is simply to have the middleware able to be conditional on a port number. It's still up to the user to configure the endpoint binding in their server.

**Comment by Tratcher** [comment]
This seems like a very specific subset of the more general "Should I run health checks?" / Auth. The more general version is likely a service where port checking is a specific implementation.

**Comment by anurse** [comment]
A service used by a Middleware to determine if it should run? Seems a little overkill. Maybe if we end up with a service driving the whole middleware behavior, but I'm not yet convinced that it's worth it yet. It wouldn't be appropriate to add HTTP concepts to the current service as it's intentionally designed to work outside of ASP.NET Core.

**Comment by Tratcher** [comment]
Auth / policy is too varied to build directly into the middleware, it should be abstracted because dev's needs and preferences on this will vary greatly. Some examples:
- local IP or port checks
- remote IP checks
- Specific header / query token
- Actual auth via basic / cookies / windows / etc..

**Comment by anurse** [comment]
It should definitely be abstracted, I'm not sure that we want to establish a whole new service for it rather than just options/events.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2579
