### ISSUE TITLE
Create custom status code middleware

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Diagnostics#42]
Consider the case where you want your application to return a nice 404 page, (or any other status code). It's impossible to find all the places in your pipeline that might return those status codes, so you want to handle them as they come back.

Proposal: A centralized middleware that can intercept responses by status code and re-execute them to generate a different response. e.g. intercept 404s (with or without a body?), change the path to `/NotFound/` and re-execute the request and let MVC generate a full page.  Compare with the ErrorHandler middleware that does this for unhandled exceptions. This one will need to be a little more complicated because you'll want to configure it per status code.

Prototype:
https://github.com/aspnetvnexthackathon/CustomStatusCodes

**Comment by Praburaj** [comment]
This is complete. Here is a sample : https://github.com/aspnet/Diagnostics/tree/dev/samples/StatusCodePagesSample
