### ISSUE TITLE
Consider adding tags on the healthcheck

### ISSUE THREAD

**Issue by ycrumeyrolle** [aspnet/Diagnostics#420]
Every healthchecks may be related to different components or features of the application. 
For example we could have tags like "database", "certificate", "critical", "authentication", "payment", ...

Tagging the healthcheck allow to request a subset of the configured healthchecks : 
/health expose all the health check results
/health/critical expose only the critical healthchecks
/health/authentication expose only the authentication related healthchecks
...

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2575
