### ISSUE TITLE
Healthcheck should be DI compatible

### ISSUE THREAD

**Issue by ycrumeyrolle** [aspnet/Diagnostics#421]
Healthcheck a commonly based on existing classes and/or existing options. 
Such objects should be injected within the Healthcheck without specify wiring.
The current implementation with [lambda implementation](https://github.com/aspnet/Diagnostics/blob/dev/src/Microsoft.Extensions.Diagnostics.HealthChecks/HealthChecksBuilderAddCheckExtensions.cs#L36) is not very DI-friendly.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2574
