### ISSUE TITLE
Remove StackTraceTest.cs and port gaps to aspnet/Common's StackTraceHelperTest

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Diagnostics#422]
StackTraceTest essentially test implementation details of the shared source helper StackTraceHelper which has it's own set of tests. We should port any missing test scenarios to the Common repo and delete this test type.

The type to delete: https://github.com/aspnet/Diagnostics/blob/dev/test/Microsoft.AspNetCore.Diagnostics.Tests/StackTraceTest.cs

**Comment by Eilon** [comment]
Knock yourself out.

**Comment by pranavkm** [comment]
We cover all of the scenarios covered by these tests in Common. No gaps to port.
