### ISSUE TITLE
Adding request headers on the ExceptionHandler throws exception

### ISSUE THREAD

**Issue by jchannon** [aspnet/Diagnostics#425]
With the ExceptionHandler middleware in place when an exception is thrown and the exception middleware then routes to the defined handler, if that handler adds headers to the request it throws.  Is that by design?

**Comment by davidfowl** [comment]
If the response already started (headers written already) then yes.

**Comment by jchannon** [comment]
Agree I can see that in the source but it checks for that and then throws so I know the response has not started as the exception handler delegate gets passed that and tries to call the route to handle the error. See the Botwin sample app

**Comment by davidfowl** [comment]
What's the exception?

**Comment by jchannon** [comment]
I throw a new Exeption("oops"). Not sure what the exception that is caught
by the mw is. Need to add logging or pray to the tooling gods I can debug
the mw on a Mac :)

**Comment by jchannon** [comment]
The MW throws `System.ArgumentException: An item with the same key has already been added. Key: HOWDY` that was added on the initial request then that route was hit again when the mw redirected/reexecuted it and hence the exception

**Comment by Tratcher** [comment]
That's a normal IDictionary exception. Using the indexer to overwrite or the Append method to add should work.
