### ISSUE TITLE
Rename ErrorHandler and its associated types/extensions

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/Diagnostics#43]
As stated here by @Tratcher (https://github.com/aspnet/Security/issues/55#issuecomment-59231290), the "ErrorHandler is just for unhandled exceptions". This general/generic name is terribly confusing, as it gives you the impression that it's meant to handle every kind of errors and not just uncaught exceptions.

`ExceptionHandler`, `UnhandledExceptionHandler` or `UncaughtExceptionHandler` might be better names.

**Comment by Eilon** [comment]
Need to come up with some names...

* `ErrorHandler`
 * Needs to say something about being specifically about exceptions
* `ErrorPage`
 * Needs to say something about being specifically about exceptions
 * Also needs to say something about being for development mode only

**Comment by kichalla** [comment]
- `ErrorHandler` is to be named to `UseExceptionHandler`
- `ErrorPage` is to be named to `UseDeveloperExceptionPage`

**Comment by kichalla** [comment]
c46615dc534b55916e3c63bc9b0db89699b7c921
