### ISSUE TITLE
Add tags to health checks

### ISSUE THREAD

**Issue by RobCannon** [aspnet/Diagnostics#467]
Instead of naming (or in addition to naming), it would be great if I could apply tags when health checks are created and then use those to filter the health checks when creating the health check endpoints.  So:

```
services
                .AddHealthChecks()
                .AddCheck(new { "live", "ready", "diagnostic"}, () => Task.FromResult(HealthCheckResult.Healthy()))
                .AddCheck(new { "ready", "diagnostic"}, new ReadinessHealthCheck())
                .AddCheck(new { "diagnostic"}, new InDepthHealthCheck());
```

```
                // Filters the set of health checks run by this middleware
    app.UseHealthChecks("/health/live", new HealthCheckOptions()
            {
                HealthCheckTags = { "live" }
            });
    app.UseHealthChecks("/health/ready", new HealthCheckOptions()
            {
                HealthCheckTags = { "ready" }
            });
    app.UseHealthChecks("/health/diagnostic", new HealthCheckOptions()
            {
                HealthCheckTags = { "diagnostic" }
            });
```

The diagnostic health check would include all of the health checks.

Maybe just a Category property for the Health Check would be enough and the filter could have multiple Categories for the filter.

The main difference between this and just listing the names for each health check is the information about where the Health Check is used is on the same line where the Health Check is defined.  Otherwise, if you have a lot of health checks, it is too easy to add a new health check and forget to add it to the list of health checks used by an endpoint at a different point in source code.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @RobCannon.
@glennc, what are your thoughts regarding this?

**Comment by rynowak** [comment]
Done

**Comment by RobCannon** [comment]
Thanks!
