### ISSUE TITLE
Alive check, readiness check... where is the busy check?

### ISSUE THREAD

**Issue by naymore** [aspnet/Diagnostics#476]
I recently wondered if service fabric shuts down service instances (stateless) gracefully. It doesn't.
I am aware of the health checking features in k8s and wondered why nobody sees any benefit in checking a service instance's (pod) busy state. For example if a service instance is drained but is still processing requests the orchestrator should wait until all pending jobs finished gracefully. Or be forcefully killed after a certain amount of time.

**Comment by chuanboz** [comment]
Service Fabric has load reporting and load metric, have you considered using that for busy load ballance? that's natively supported by service fabric.

**Comment by glennc** [comment]
@naymore That functionality is kind of built into the stack already. Once ASP.NET gets a shutdown notification from the orchestrator it will attempt to drain all requests before terminating. Once the timeout has expired they will be killed and the process end. Is there something more that you would expect here?

**Comment by natemcmaster** [comment]
I'm closing as there doesn't appear to be any action item. We're going to archive this repo which makes this read-only. If you have additional feedback on this subject, please use https://github.com/aspnet/AspNetCore
