### ISSUE TITLE
Development in both Windows and Mac

### ISSUE THREAD

**Issue by biodavidjm** [aspnet/Diagnostics#495]
Hi! we are developing a web app using dotnet on two different operating systems: The main developer is working on Windows and I am doing it on the Mac, both using Visual Studio. Everything was working fine and I was able to apply changes and build it locally on the Mac to test them.

But now something has changed and Visual Studio crashes every time that I am trying to build the application. And the issue seems to be clear: it is changing `/` by `\` when trying to find libraries. I got this "Application output":

```
[41m[30mfail[39m[22m[49m: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[0]
      An unhandled exception has occurred while executing the request
System.IO.DirectoryNotFoundException: Could not find a part of the path '/Users/djm/VisualStudio/bioNeNa/bioNeNa.Web/wwwroot\lib\bootstrap\dist\css\themes'.
```
Any way to solve this problem? thanks!

**Comment by Tratcher** [comment]
This issue was moved to aspnet/Home#3566
