### ISSUE TITLE
JsonResponseWriter in Health checks assembly

### ISSUE THREAD

**Issue by CarlosLanderas** [aspnet/Diagnostics#523]
Hello!. My name is Carlos and I am a core team member of Beatpulse.

I would like to suggest adding a default json response writer inside HealtChecks package because retrieving the health check report instead of status codes would be a common escenario.

I don't mean this response writer should be internally registered when wiring the services but at least available in the assembly 

The main motivation for this is removing a dependency from the project as right now to use BeatPulse.UI you have to install an extra package containing the client UI response writer. I think this absence will also force most HealtChecks users to implement the Json Response Writer by themselves very often.

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.UI.Client/UIResponseWriter.cs

What do you think about this idea?

Thanks

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @CarlosLanderas.
@rynowak  thoughts?

**Comment by rynowak** [comment]
We discussed this during 2.2 and we have no plans to do this.  If we put something in the box it won't change (**ever**).  We definitely intend for libraries to fill this gap (or your own code).

The kind of output you want (if any) is highly dependent on what the consumer/monitoring service is. We don't want to create our own format.
