### ISSUE TITLE
Error Page: regression: In Mono function names now show up but without file names/line info

### ISSUE THREAD

**Issue by borgdylan** [aspnet/Diagnostics#54]
If I enable my compiler's debug functionality (I am not using c#), and let an exception get caught by the error page middle ware I do not get t see the file names and line numbers present in the exception stack trace. Before the fix done in https://github.com/aspnet/Diagnostics/pull/50 I could not see function names (fixed by that PR) but I could see the file names and line numbers whenever i enabled debug mode while compiling and passed --debug to mono.

**Comment by Praburaj** [comment]
This is fixed.
