### ISSUE TITLE
Error page needs to have an easily copyable exception message and stack trace

### ISSUE THREAD

**Issue by Eilon** [aspnet/Diagnostics#60]
See https://github.com/aspnet/Helios/issues/75.

**Comment by back5576** [comment]
Above link is bad. I have same question - how to get exception info?

**Comment by Eilon** [comment]
The link is valid, but it's to a private repo (that we hope to make public... soon!).

The info in that bug is this:

------------------

The current text of the exception message and stack trace does not copy well into places such as bug reports and email. I recommend having something like one of these:

1. An HTML comment in the page that if you View/Source on you can copy the raw text
2. Have a button in the page that shows a read-only textarea that has the raw text
3. Perhaps in addition to (2), have a button that copies the text to the clipboard

**Comment by back5576** [comment]
Thanks

**Comment by Eilon** [comment]
Dup of https://github.com/aspnet/Diagnostics/issues/33.
