### ISSUE TITLE
Allow simple custom error pages for specific HTTP status codes

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Diagnostics#66]
IIS provides a mechanism for configuring custom pages/files to be shown when specific HTTP status codes occur, e.g. show 404.html when a 404 happens.

We should have a similar feature that works cross-server and is provided by the diagnostics package.

**Comment by Tratcher** [comment]
A few things we did decide on:
- The primary purpose is to generate human readable HTML pages, preferably something that matches the rest of the site's style.
- It needs to be configurable per status code. The default behavior for any given status code is open to discussion.
- Only handle responses with no body, do not support replacing the body.
- A simple scenario would do a client side redirect to another URL responsible for rendering the page (with a 200 status code).
- Note: Responses should be greater than 500 bytes (?), IE will not show small error responses.

Outstanding Issues:

How should you generate the body?
- There are lots of problems with trying to re-execute the request to let MVC or static files generate the body.
  - They'll overwrite the status code
  - They may try to honor request cache headers (if-not-match) with strange side-effects
  - They may generate response cache headers. Caching errors is bad.

How can you avoid breaking an API request?
- Do you need to check the Accept header to avoid sending HTML to client expecting XML/JSON?
- For the redirect-to-page scenario, how do we suppress that for API calls?

**Comment by blowdart** [comment]
Surely an API request should ignore the body and just go off status code, otherwise they'd have barfed on IIS anyway :)

**Comment by Praburaj** [comment]
Planning to finish this coming week.

**Comment by Praburaj** [comment]
This change went in today.
