### ISSUE TITLE
Improve design of default error page

### ISSUE THREAD

**Issue by avanderhoorn** [aspnet/Diagnostics#78]
It was mentioned in the NDC London talk that the design of the current error page could be improved to be more inline with the Helios error page. I wouldn't mind having a crack at this but didn't want to start without the go ahead. Note, this work wouldn't fix the problems with this page that other issues have brought up, it would just "improve" the design. // @DamianEdwards @davidfowl (it was during their talk)

**Comment by Eilon** [comment]
Kind of related to https://github.com/aspnet/Diagnostics/issues/33

**Comment by Eilon** [comment]
No plans at this time to implement this.
