### ISSUE TITLE
Remove ErrorPageOptions from ErrorPage middleware

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Diagnostics#80]
This is useless now as we use different middleware based on the environment of the site.

**Comment by Tratcher** [comment]
ErrorPageOptions has a lot more settings than just On or Off. E.g. how many lines of source code to show.

**Comment by Eilon** [comment]
Eh, but if it's for local/debug only then you don't really need all those settings. And who would really configure how many lines of source to show? ASP.NET never had that option, and if you are able to change that option to get more info, you might as well look at the actual source.

**Comment by Tratcher** [comment]
Everything has been removed except SourceCodeLineCount.

**Comment by davidfowl** [comment]
This can be closed then. With the proper tags
