### ISSUE TITLE
Prefer the new encoders over the old WebUtility APIs

### ISSUE THREAD

**Issue by GrabYourPitchforks** [aspnet/Diagnostics#89]
There are still some call sites in the Diagnostics code base that invoke WebUtility.HtmlEncode.  These call sites should instead use IHtmlEncoder.HtmlEncoder.

**Comment by GrabYourPitchforks** [comment]
The types `IHtmlEncoder`, `IJavaScriptStringEncoder`, and `IUrlEncoder` are in the Microsoft.AspNet.WebUtilities package. To register them from within your own AddServices method, reference the Microsoft.AspNet.Http.Extensions package and call `AddEncoders`.

**Comment by muratg** [comment]
Looks like the PR is pending?  @Praburaj

**Comment by Praburaj** [comment]
Yes. It will be fixed soon as I found an issue with the `GetHtmlEncoder` extension.
