### ISSUE TITLE
Add basic diagnostic tools

### ISSUE THREAD

**Issue by djanosik** [aspnet/Diagnostics#92]
I think ASP.NET 5 should provide some basic diagnostic tools. Perhaps something like [Glimpse](http://getglimpse.com/) or [Tracy](http://tracy.nette.org/en/).

**Comment by davidfowl** [comment]
I think you should use Glimpse (when it supports ASP.NET 5 of course). There's also different kinds of Diagnostics. What specifically are you talking about?

/cc @avanderhoorn

**Comment by avanderhoorn** [comment]
For Glimpse, efforts for vNext support are well on the way - http://github.com/avanderhoorn/Glimpse.Prototype.

**Comment by JT703** [comment]
@davidfowl - I can't speak for @djanosik but I've been looking for something to profile across platforms. Is there anything I can use right now? @avanderhoorn - Is that Glimpse prototype usable?

**Comment by avanderhoorn** [comment]
Not currently, its mainly infrastructure support and the framework foundations, etc. If it helps, the plan is for it to be fully supported cross platform.

**Comment by JT703** [comment]
That's great to hear, @avanderhoorn - any ETA on when something would be ready to use?

Also, @davidfowl - Visual Studio 2015 does some profiling, but I couldn't get it to profile my .NET 5 website. Is that not supported yet or am I just doing something wrong?

**Comment by davidfowl** [comment]
Profiling doesn't work yet for ASP.NET 5 projects. You can file an issue on the Tooling repo but that's known.
