### ISSUE TITLE
Database Error Page: Update migration commands that reference 'k ef ...'

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/Diagnostics#98]
cc @rustd

**Comment by rowanmiller** [comment]
The commands are currently still `k`, you can run them via `dnx` but it's more complex than using `k`. Will update once a simple command format is supported.

**Comment by danroth27** [comment]
k.cmd is being removed: #1473

**Comment by rowanmiller** [comment]
Already checked in... just forgot to close out this issue :smile: 
https://github.com/aspnet/Diagnostics/commit/f644aea3b1c8be13da242f78474772bc36344ad2
